$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: ../scripts/
command: python train.py
environment: azureml:AzureML-sklearn-0.24-ubuntu18.04-py37-cpu@latest
compute: tnt-ml-compute
experiment_name: diabetes-training
description: "Training job for diabetes model"
